title: Creatures by Type
nav:
  - index.md
  - aberration
  - beast
  - celestial
  - construct
  - dragon
  - elemental
  - fey
  - fiend
  - giant
  - humanoid
  - icon
  - monstrosity
  - ooze
  - plant
  - undead
  - ...
