title: Extreme Circuit of the Outer Planes
nav:
  - index.md
  - paradisia.md
  - elysium.md
  - olympus.md
  - asgard.md
  - tempest.md
  - oblivion.md
  - abyss.md
  - abaddon.md
  - diyu.md
  - gehenna.md
  - hell.md
  - carnage.md
  - axiom.md
  - academia.md
  - heaven.md
  - nirvana.md
  - ...
